services:
  router:
    depends_on:
      # self signed should run first, so override depends_on
      - certbot
      - frontend
      - backend
      - agent-api
      - grace-pty
      - will-pty

# self-signed cert (for Development Environment)
  certbot:
    image: alpine:latest
    container_name: hermesai-selfsigned
    depends_on: !reset []
    entrypoint: >
      sh -c "apk add --no-cache openssl &&
      mkdir -p /etc/letsencrypt/live/hermesai.dev &&
      openssl req -x509 -nodes -days 365 -subj '/CN=hermesai.dev' -newkey rsa:2048 -keyout /etc/letsencrypt/live/hermesai.dev/privkey.pem -out /etc/letsencrypt/live/hermesai.dev/fullchain.pem"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - hermesnet
