services:
  database:
    build: ./apps/database
    container_name: hermesai-db
    expose:
      - "5432"
    environment:
      POSTGRES_DB: hermesaidb
      POSTGRES_USER: hermesai_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./apps/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hermesnet

  agent-api:
    build: ./apps/api
    container_name: hermesai-api
    volumes:
      - ${TOKEN_MAP_PATH:-./apps/api/tokens}:/4d24721f7fe5084b6f4e0c93eca86954:ro
    expose:
      - "8081"
    networks:
      - hermesnet
    environment:
      - RUST_LOG=debug

  grace-pty:
    build: ./apps/pty
    container_name: hermesai-grace-pty
    expose:
      - "8080"
    networks:
      - hermesnet


  will-pty:
    build: ./apps/pty
    container_name: hermesai-will-pty
    expose:
      - "8080"
    networks:
      - hermesnet


  backend:
    build: ./apps/execution-sandbox/sandbox_server
    container_name: hermesai-backend
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://hermesai_user:secret@database:5432/hermesaidb
      PYTHONUNBUFFERED: 1
    expose:
      - "8080"
    volumes:
      - ./apps/execution-sandbox:/app
    networks:
      - hermesnet
    command: ["python", "-m", "sandbox_server.app"]

  frontend:
    build: ./apps/dropcode-client
    container_name: hermesai-frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    command: ["nginx", "-g", "daemon off;"]
    expose:
      - "80"
    networks:
      - hermesnet

  router:
    build: ./apps/execution-sandbox/terminal
    container_name: hermesai-router
    depends_on:
      - frontend
      - backend
      - agent-api
      - grace-pty
      - will-pty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/execution-sandbox/terminal/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot               # <-- CHALLENGE FILES
      - ./certbot/conf:/etc/letsencrypt              # <-- CERT STORAGE
    networks:
      - hermesnet
    environment:
      - ROUTER_MODE=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  certbot:
    image: certbot/certbot
    container_name: hermesai-certbot
    depends_on:
      - router
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --staging --standalone
      --register-unsafely-without-email --agree-tos
      -d hermesai.dev &&
      mkdir -p /var/www/certbot/live/hermesai.dev &&
      cp -r /etc/letsencrypt/live/hermesai.dev/* /var/www/certbot/live/hermesai.dev/"
    networks:
      - hermesnet

#  selfsigned:
#    image: alpine:latest
#    container_name: hermesai-selfsigned
#    command: >
#      sh -c "apk add --no-cache openssl &&
#      mkdir -p /etc/letsencrypt/live/hermesai.dev &&
#      openssl req -x509 -nodes -days 365 -subj '/CN=hermesai.dev' -newkey rsa:2048 -keyout /etc/letsencrypt/live/hermesai.dev/privkey.pem -out /etc/letsencrypt/live/hermesai.dev/fullchain.pem"
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#    networks:
#      - hermesnet


volumes:
  db_data:

networks:
  hermesnet:
    driver: bridge
  bridge:
    driver: bridge
