[namespaces]
enable = false
pid = true
mount = true
user = true
net = false

[limits]
cpu_ms = 300000
mem_mb = 512
fsize_mb = 128
nproc = 256
nofile = 4096

[timeouts]
job_ms = 600000
grace_ms = 5000
idle_session_ms = 1200000
