name: Build All HermesAI Docker Images (No Push)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all HermesAI images
        run: |
          docker build -t whb4118/hermesai-db:latest ./apps/database
          docker build -t whb4118/hermesai-api:latest ./apps/api
          docker build -t whb4118/hermesai-pty:latest ./apps/pty
          docker build -t whb4118/hermesai-flask:latest ./apps/execution-sandbox/sandbox_server
          docker build -t whb4118/hermesai-client:latest ./apps/dropcode-client
          docker build -t whb4118/hermesai-router:latest ./apps/execution-sandbox/terminal